Stop duplicate output files showing up in the index.

diff --git a/.github/workflows/build-and-publish-worksheets.yml b/.github/workflows/build-and-publish-worksheets.yml
--- a/.github/workflows/build-and-publish-worksheets.yml
+++ b/.github/workflows/build-and-publish-worksheets.yml
@@ -66,7 +66,8 @@ jobs:
           echo Generating $HTML_FILE
           PATH="$SRC_DIR/Strypify-linux-x64:$PATH" asciidoctor -v --trace -r "$SRC_DIR/strypify-plugin.rb" -o "$HTML_FILE" "$SRC_FILE" || echo "Failed to generate $HTML_FILE -- see logs"
           echo Generating $PDF_FILE
-          PATH="$SRC_DIR/Strypify-linux-x64:$PATH" asciidoctor-pdf -v --trace -r "$SRC_DIR/strypify-plugin.rb" -o "$PDF_FILE" "$SRC_FILE" || echo "Failed to generate $PDF_FILE -- see logs" 
+          PATH="$SRC_DIR/Strypify-linux-x64:$PATH" asciidoctor-pdf -v --trace -r "$SRC_DIR/strypify-plugin.rb" -o "$PDF_FILE" "$SRC_FILE" || echo "Failed to generate $PDF_FILE -- see logs"
+          rm $SRC_FILE 
         done
         # Show all the generated files:
         find .
