Fixed more path issues

diff --git a/.github/workflows/build-and-publish-worksheets.yml b/.github/workflows/build-and-publish-worksheets.yml
--- a/.github/workflows/build-and-publish-worksheets.yml
+++ b/.github/workflows/build-and-publish-worksheets.yml
@@ -61,10 +61,12 @@ jobs:
         for f in $FILES; do
           HTML_FILE="$(basename "${f%.adoc}.html")"
           PDF_FILE="$(basename "${f%.adoc}.pdf")"
+          cp $f .
+          SRC_FILE = "$(basename "$f")"
           echo Generating $HTML_FILE
-          PATH="$SRC_DIR/Strypify-linux-x64:$PATH" asciidoctor -v --trace -r "$SRC_DIR/strypify-plugin.rb" -o "$HTML_FILE" "$f" || echo "Failed to generate $HTML_FILE -- see logs"
+          PATH="$SRC_DIR/Strypify-linux-x64:$PATH" asciidoctor -v --trace -r "$SRC_DIR/strypify-plugin.rb" -o "$HTML_FILE" "$SRC_FILE" || echo "Failed to generate $HTML_FILE -- see logs"
           echo Generating $PDF_FILE
-          PATH="$SRC_DIR/Strypify-linux-x64:$PATH" asciidoctor-pdf -v --trace -r "$SRC_DIR/strypify-plugin.rb" -o "$PDF_FILE" "$f" || echo "Failed to generate $PDF_FILE -- see logs" 
+          PATH="$SRC_DIR/Strypify-linux-x64:$PATH" asciidoctor-pdf -v --trace -r "$SRC_DIR/strypify-plugin.rb" -o "$PDF_FILE" "$SRC_FILE" || echo "Failed to generate $PDF_FILE -- see logs" 
         done
         # Show all the generated files:
         find .
@@ -78,13 +80,13 @@ jobs:
           for f in $FILES; do
             fname=$(basename "${f%.adoc}.html")
             echo "<li><a href='./$fname'>$fname</a>"
-            if [ ! -f $fname ]; then
+            if [ ! -f "$OUTPUT_DIR/$fname" ]; then
               echo " (failed to generate -- see logs)"
             fi
             echo "</li>"
             fname=$(basename "${f%.adoc}.pdf")
             echo "<li><a href='./$fname'>$fname</a>"
-            if [ ! -f $fname ]; then
+            if [ ! -f "$OUTPUT_DIR/$fname" ]; then
               echo " (failed to generate -- see logs)"
             fi
             echo "</li>"
